name: "test"
on: ["push", "pull_request", "workflow_dispatch"]

jobs:
    test:
        runs-on: "ubuntu-latest"
        strategy:
            matrix:
                java: ["17", "21", "24"]
                distribution: ["temurin", "semeru"]
                exclude:
                  - java: "24"
                    distribution: "semeru"
        name: "Java ${{ matrix.java }} (${{ matrix.distribution }})"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
            - name: "Validate Gradle Wrapper"
              uses: "gradle/actions/wrapper-validation@v4"
            - name: "Set up JDKs"
              uses: "actions/setup-java@v4"
              with:
                java-version: "${{ matrix.java }}"
                distribution: "${{ matrix.distribution }}"
            - name: "Set Gradle Permissions"
              run: "chmod +x ./gradlew"
            - name: "Run Tests"
              run: "./gradlew test"
