name: "Java CI with Gradle"
on: [ "push", "pull_request", "workflow_dispatch" ]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v5"
      - name: "Set up JDK 17"
        uses: "actions/setup-java@v5"
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Validate Gradle Wrapper"
        uses: "gradle/actions/wrapper-validation@v5"
      - name: "Make Gradle wrapper executable"
        run: "chmod +x ./gradlew"
      - name: "Test with Gradle"
        run: "./gradlew test"
